### ISSUE TITLE
Still active ?

### ISSUE THREAD

**Issue by IDerr** [ProjectBlackFalcon/DatBot#2]
Hello,
Est-ce que ce projet est toujours actif ?

Merci du boulot :D

**Comment by LysandreJik** [comment]
Bonsoir ! Le projet est toujours actif mais en pause par manque de temps 😊
Pourquoi, tu es intéressé ?

**Comment by IDerr** [comment]
Yep, j'ai lu le code et c'est m’intéresse pas mal :D T'as un discord ou autre pour discuter ?

**Comment by skyforce77** [comment]
Tout pareil o/

**Comment by BaptisteBdn** [comment]
Bonsoir, le projet est un peu vieux et on manque de temps pour le continuer mais si ça vous intéresse on peut en discuter ! Mon discord : Centaurefox#4312, je vous mettrais en contact avec les deux autres collaborateurs aussi !

**Comment by IDerr** [comment]
Thanks c'est ajoute
