### ISSUE TITLE
ProtocolBuilder ne genere pas certaines classes

### ISSUE THREAD

**Issue by IDerr** [ProjectBlackFalcon/DatBot#3]
Bonjour, 
le protocolbuilder ne genere pas certaines classes comme : 
AbstractCharacterInformation
CharacterBaseCharacteristic
VersionExtended
SellerBuyerDescriptor

Merci pour votre boulot :D

**Comment by BaptisteBdn** [comment]
En effet : 
`			if (msg.getName().equals("VersionExtended") || msg.getName().equals("SellerBuyerDescriptor") || msg.getName().equals("AbstractCharacterInformation") || msg.getName().equals("CharacterBaseCharacteristic")) {
				continue; 
			}`

Je n'en avais pas besoin de mon côté et je ne voulais pas que les classes soient régénérés. Tu peux commenter le bout de code et les classes seront régénérés.

**Comment by IDerr** [comment]
Ok cool, merci
